//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1022
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RT.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool run_onlyShowFailedScenarios {
            get {
                return ((bool)(this["run_onlyShowFailedScenarios"]));
            }
            set {
                this["run_onlyShowFailedScenarios"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("jdoe")]
        public string target_dbUsername {
            get {
                return ((string)(this["target_dbUsername"]));
            }
            set {
                this["target_dbUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string target_dbPassword {
            get {
                return ((string)(this["target_dbPassword"]));
            }
            set {
                this["target_dbPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tortoisemerge")]
        public string fileDiffer_executable {
            get {
                return ((string)(this["fileDiffer_executable"]));
            }
            set {
                this["fileDiffer_executable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/base:\"%expectedFilename%\" /mine:\"%actualFilename%\"")]
        public string fileDiffer_parameters {
            get {
                return ((string)(this["fileDiffer_parameters"]));
            }
            set {
                this["fileDiffer_parameters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string app_version {
            get {
                return ((string)(this["app_version"]));
            }
            set {
                this["app_version"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dbsnmp, oracle_ocm, outln, sys, sysman, system, tsmsys")]
        public string schemas_excludedSchemas {
            get {
                return ((string)(this["schemas_excludedSchemas"]));
            }
            set {
                this["schemas_excludedSchemas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string repos_exportPath {
            get {
                return ((string)(this["repos_exportPath"]));
            }
            set {
                this["repos_exportPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string repos_xmlEditor {
            get {
                return ((string)(this["repos_xmlEditor"]));
            }
            set {
                this["repos_xmlEditor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string plsql_editor {
            get {
                return ((string)(this["plsql_editor"]));
            }
            set {
                this["plsql_editor"] = value;
            }
        }
    }
}
